import { ReactNode } from 'react'
import { Roboto } from 'next/font/google'
import './globals.css'
import { Providers } from './providers/providers'

const roboto = Roboto({
	subsets: ['latin'],
	weight: ['400', '700'],
})

export const metadata = {
	title: 'Ignite Shop',
	description: 'Generated by create next app',
}
export default function RootLayout({ children }: { children: ReactNode }) {
	return (
		<html lang='pt-BR'>
			<Providers>
				<body
					className={`${roboto.className} h-screen w-screen bg-Grayscale/Background relative`}
				>
					<div className='absolute top-32 z-0'>{children}</div>
				</body>
			</Providers>
		</html>
	)
}
